# Generated by Django 5.0.1 on 2024-02-05 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinLengthValidator(18)])),
                ('dob', models.DateField()),
                ('numberOfClass', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
            ],
        ),
    ]
