# Generated by Django 5.0.1 on 2024-02-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachermanagement', '0002_alter_teacher_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='numberOfClass',
            field=models.IntegerField(),
        ),
    ]
